#!/usr/bin/env bash
# ============================================
# RECO-TRADING DASHBOARD - INSTALLER
# ============================================
# 100% PORTABLE — everything installs relative
# to the folder where this script lives.
# Just copy the project folder anywhere and run:
#   ./install.sh
#
# HOW IT WORKS:
# - Detects the project directory automatically
# - Sets DATABASE_URL to the correct absolute path
#   for this system (works on ANY Linux/Unix)
# - All internal paths are computed dynamically
# ============================================
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ---- Detect where this script is located ----
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║       RECO-TRADING DASHBOARD INSTALLER       ║${NC}"
echo -e "${CYAN}║    Professional Crypto Trading System         ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}[INFO]${NC} Project directory: $ROOT_DIR"

# Parse flags
FORCE=false
if [[ "$1" == "--force" ]] || [[ "$1" == "-f" ]]; then
  FORCE=true
  echo -e "${YELLOW}  ⚠ Force mode enabled — will rebuild everything${NC}"
fi

# ---- Check OS ----
OS=$(uname -s 2>/dev/null || echo "unknown")
echo -e "${BLUE}[INFO]${NC} Operating system: $OS"

SKIP_COUNT=0
INSTALL_COUNT=0

# ---- Helper: mark step as skipped ----
skip_step() {
  SKIP_COUNT=$((SKIP_COUNT + 1))
  echo -e "${GREEN}  ✓${NC} $1 (already installed)"
}

# ---- Helper: mark step as installing ----
install_step() {
  INSTALL_COUNT=$((INSTALL_COUNT + 1))
  echo -e "${BLUE}  →${NC} $1"
}

# ---- Step 1: Install Bun ----
echo ""
echo -e "${YELLOW}[1/6]${NC} Checking Bun runtime..."
if command -v bun &>/dev/null; then
  BUN_VERSION=$(bun --version)
  skip_step "Bun v${BUN_VERSION}"
else
  install_step "Installing Bun..."
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
  # Also add to profile if not there
  for PROFILE_FILE in "$HOME/.bashrc" "$HOME/.profile" "$HOME/.zshrc"; do
    if [ -f "$PROFILE_FILE" ] && ! grep -q ".bun/bin" "$PROFILE_FILE" 2>/dev/null; then
      echo 'export PATH="$HOME/.bun/bin:$PATH"' >> "$PROFILE_FILE"
    fi
  done
  echo -e "${GREEN}  ✓${NC} Bun installed: $(bun --version)"
fi

# ---- Step 2: Create / fix .env ----
echo ""
echo -e "${YELLOW}[2/6]${NC} Configuring environment (.env)..."

# Database path: dynamically computed from where the script is right now.
# This always points to <project>/data/reco_trading.db no matter
# where the folder is located on any system.
DB_DIR="$ROOT_DIR/data"
DB_FILE="$DB_DIR/reco_trading.db"
DB_URL="file:$DB_FILE"

if [ -f .env ]; then
  skip_step ".env already exists (API keys preserved)"
  echo -e "${BLUE}  →${NC} To regenerate: delete .env and run install.sh again"

  # ---- Auto-fix DATABASE_URL to match current location ----
  CURRENT_DB_URL=$(grep -E '^DATABASE_URL=' .env 2>/dev/null | head -1 | cut -d'=' -f2- | tr -d '"' | tr -d "'")
  CURRENT_DB_PATH="${CURRENT_DB_URL#file:}"

  NEED_FIX=false
  if [ -z "$CURRENT_DB_URL" ]; then
    NEED_FIX=true
    echo -e "${YELLOW}  ⚠${NC} DATABASE_URL missing from .env"
  elif [ "$CURRENT_DB_PATH" != "$DB_FILE" ]; then
    NEED_FIX=true
    echo -e "${YELLOW}  ⚠${NC} DATABASE_URL points to: $CURRENT_DB_PATH"
    echo -e "${YELLOW}  ⚠${NC} Correcting to: $DB_FILE"
  fi

  if [ "$NEED_FIX" = true ]; then
    if grep -q '^DATABASE_URL=' .env 2>/dev/null; then
      sed -i "s|^DATABASE_URL=.*|DATABASE_URL=$DB_URL|" .env
    else
      echo "DATABASE_URL=$DB_URL" >> .env
    fi
    echo -e "${GREEN}  ✓${NC} DATABASE_URL corrected to: $DB_URL"
  fi
else
  install_step "Creating .env file..."

  # Generate random session secret
  SESSION_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "reco-trading-secret-change-me-$(date +%s)")

  cat > .env << ENVFILE
# ============================================
# RECO-TRADING - Environment Configuration
# ============================================
# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Path auto-detected: $ROOT_DIR
# ============================================

# ---- DATABASE ----
# SQLite database (auto-detected path for this system)
DATABASE_URL=$DB_URL

# ---- BROKER CREDENTIALS ----
# IMPORTANT: Configure OANDA as primary broker
# OANDA: https://www.oanda.com/
OANDA_ACCOUNT_ID=your_oanda_account_id_here
OANDA_API_TOKEN=your_oanda_api_token_here

# Active broker: oanda | weltrade_mt5
BROKER_ACTIVE=oanda

# Weltrade MT5 bridge (optional)
WELTRADE_MT5_LOGIN=your_mt5_login
WELTRADE_MT5_PASSWORD=your_mt5_password
WELTRADE_MT5_SERVER=your_mt5_server
WELTRADE_MT5_IS_DEMO=true
WELTRADE_MT5_BRIDGE_URL=http://127.0.0.1:5001
# ---- TRADING CONFIG ----
TRADING_SYMBOL=XAU_USD
PRIMARY_TIMEFRAME=5m
CONFIRMATION_TIMEFRAME=15m
# Use testnet (true = testnet with fake money, false = real money!)
OANDA_IS_DEMO=true

# ---- RISK MANAGEMENT ----
RISK_PER_TRADE=1.0
MAX_DAILY_LOSS=3.0
MAX_DRAWDOWN=10.0
MAX_TRADES_PER_DAY=120
MIN_CONFIDENCE=0.62

# ---- CAPITAL ----
INITIAL_CAPITAL=1000.0
CAPITAL_MODE=MEDIUM

# ---- DASHBOARD ----
DASHBOARD_PORT=3000
DASHBOARD_AUTH_ENABLED=false
DASHBOARD_USERNAME=admin
DASHBOARD_PASSWORD=reco_trading_2024

# ---- SESSION ----
NEXTAUTH_SECRET=$SESSION_SECRET
NEXTAUTH_URL=http://localhost:3000

# ---- FLASK BOT (optional) ----
BOT_API_URL=http://localhost:9000
ENVFILE

  chmod 600 .env
  echo -e "${GREEN}  ✓${NC} .env created successfully"
  echo -e "${BLUE}  →${NC} Edit .env and add your broker credentials before trading!"
fi

# ---- Create local directories ----
echo -e "${BLUE}  →${NC} Ensuring local directories..."
mkdir -p "$DB_DIR"
mkdir -p "$ROOT_DIR/logs"
echo -e "${GREEN}  ✓${NC} Directories ready: data/ logs/"

# ---- Step 3: Install Node.js dependencies ----
echo ""
echo -e "${YELLOW}[3/6]${NC} Installing dependencies..."

if [ -d "node_modules" ] && ([ -f "bun.lock" ] || [ -f "bun.lockb" ]) && [ "$FORCE" != "true" ]; then
  # Check if lockfile is newer than node_modules
  LOCK_FILE="bun.lock"
  [ ! -f "$LOCK_FILE" ] && LOCK_FILE="bun.lockb"
  LOCK_MTIME=$(stat -c %Y "$LOCK_FILE" 2>/dev/null || stat -f %m "$LOCK_FILE" 2>/dev/null || echo 0)
  NM_MTIME=$(stat -c %Y node_modules 2>/dev/null || stat -f %m node_modules 2>/dev/null || echo 0)

  if [ "$NM_MTIME" -gt "$LOCK_MTIME" ] && [ "$NM_MTIME" -ne 0 ]; then
    skip_step "node_modules up to date"
  else
    echo -e "${BLUE}  →${NC} Dependencies may be outdated, updating..."
    bun install
    echo -e "${GREEN}  ✓${NC} Dependencies updated"
  fi
elif [ "$FORCE" = "true" ]; then
  install_step "Force reinstalling all dependencies..."
  bun install
  echo -e "${GREEN}  ✓${NC} Dependencies installed"
else
  install_step "Installing dependencies (this may take a minute)..."
  bun install
  echo -e "${GREEN}  ✓${NC} Dependencies installed"
fi

# ---- Step 4: Setup Prisma + Database ----
echo ""
echo -e "${YELLOW}[4/6]${NC} Setting up database..."

# Ensure data directory exists before Prisma operations
mkdir -p "$DB_DIR"

# Override DATABASE_URL to match current location (even if .env is stale)
export DATABASE_URL="$DB_URL"

# Generate Prisma client
echo -e "${BLUE}  →${NC} Generating Prisma client..."
bunx prisma generate 2>&1 | tail -1
echo -e "${GREEN}  ✓${NC} Prisma client generated"

# Push schema to database (idempotent — safe to run multiple times)
if [ "$FORCE" = "true" ]; then
  echo -e "${BLUE}  →${NC} Force resetting database..."
  bunx prisma db push --force-reset --skip-generate 2>&1 | tail -1
else
  echo -e "${BLUE}  →${NC} Syncing database schema..."
  bunx prisma db push --skip-generate 2>&1 | tail -1
fi
echo -e "${GREEN}  ✓${NC} Database configured"

# ---- Step 5: Build the application ----
echo ""
echo -e "${YELLOW}[5/6]${NC} Building application..."

# Always clean build caches and lock files to prevent stale type errors
echo -e "${BLUE}  →${NC} Cleaning build caches..."
rm -rf .next/lock .next/cache .next 2>/dev/null || true

if [ "$FORCE" = "true" ]; then
  install_step "Force rebuild..."
  bun run build
  echo -e "${GREEN}  ✓${NC} Build complete"
else
  install_step "Building application..."
  bun run build
  echo -e "${GREEN}  ✓${NC} Build complete"
fi

# ---- Step 6: Final checks ----
echo ""
echo -e "${YELLOW}[6/6]${NC} Final checks..."
mkdir -p "$DB_DIR"
mkdir -p "$ROOT_DIR/logs"

# Verify database file was created
if [ -f "$DB_FILE" ]; then
  DB_SIZE=$(du -h "$DB_FILE" 2>/dev/null | cut -f1)
  echo -e "${GREEN}  ✓${NC} Database ready: data/reco_trading.db ($DB_SIZE)"
else
  echo -e "${YELLOW}  ⚠${NC} Database file not found, but will be created on first run"
fi

echo -e "${GREEN}  ✓${NC} All runtime directories ready"

# ---- Summary ----
echo ""
echo -e "${CYAN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✓ INSTALLATION COMPLETE!${NC}"
echo -e "${CYAN}══════════════════════════════════════════════${NC}"
echo ""
echo -e "  Project path:     ${BLUE}$ROOT_DIR${NC}"
echo -e "  Database:         ${BLUE}data/reco_trading.db${NC}"
echo -e "  Steps skipped:    ${GREEN}${SKIP_COUNT}${NC}"
echo -e "  Steps executed:   ${BLUE}${INSTALL_COUNT}${NC}"
echo ""
echo -e "${YELLOW}NEXT STEPS:${NC}"
echo ""
echo -e "  1. ${BLUE}Edit your API keys:${NC}"
echo -e "     nano .env"
echo -e "     Set BROKER_ACTIVE, OANDA_ACCOUNT_ID and OANDA_API_TOKEN"
echo ""
echo -e "  2. ${BLUE}Start the dashboard (development):${NC}"
echo -e "     ./dev.sh"
echo ""
echo -e "  3. ${BLUE}Start the dashboard (production):${NC}"
echo -e "     ./run.sh"
echo ""
echo -e "  4. ${BLUE}Access the dashboard:${NC}"
echo -e "     http://localhost:${DASHBOARD_PORT:-3000}"
echo ""
echo -e "  ${BLUE}Tip:${NC} Run ${YELLOW}./install.sh --force${NC} to force rebuild everything"
echo ""
echo -e "${RED}⚠  WARNING:${NC}"
echo -e "  - OANDA_IS_DEMO=true (using demo, no real money)"
echo -e "  - Set to 'false' ONLY when you are ready to trade for real"
echo -e "  - Always test with demo first!"
echo ""

